### ISSUE TITLE
Version 1.5.1 creating broken documentation?

### ISSUE THREAD

**Issue by DrYSG** [onury/docma#32]
It probably is me, since I just started trying to use docma.

But when I use Chrome to load the documetation, I get a page not found error (404). (even though it should all be at http://localhost/WebView/docs/ )

```
docma-web.js:38 Uncaught Error: Page or content not found for route: {}
    at docma-web.js:38
    at Stub.callback (docma-web.js:38)
    at Stub.flush (docma-web.js:4)
    at Chunk.setError (docma-web.js:4)
    at Object.dust.render (docma-web.js:4)
    at n (docma-web.js:38)
    at r (docma-web.js:38)
    at Object.docma.render (docma-web.js:38)
    at e.apply (docma-web.js:38)
    at docma-web.js:38
(anonymous) @ docma-web.js:38
(anonymous) @ docma-web.js:38
Stub.flush @ docma-web.js:4
Chunk.setError @ docma-web.js:4
dust.render @ docma-web.js:4
n @ docma-web.js:38
r @ docma-web.js:38
docma.render @ docma-web.js:38
e.apply @ docma-web.js:38
(anonymous) @ docma-web.js:38
(anonymous) @ docma-web.js:9
n @ docma-web.js:9
(anonymous) @ docma-web.js:9
n @ docma-web.js:9
(anonymous) @ docma-web.js:9
n @ docma-web.js:9
r.dispatch @ docma-web.js:9
r.replace @ docma-web.js:9
r.start @ docma-web.js:9
window.onload @ docma-web.js:38

```

The build seemed to go fine:

```
docma -c ./docma.config.json -d ./docs -s ./scripts/*



Building documentation...

Using Template: Docma Default Template (version: 1.7.0)

Expanding source files...
Expanding: scripts\*
 » Unsupported file ignored: D:\wwwroot\WebView\scripts\Config.json
Parsing 8 Javascript file(s)...
Copying template files/directories...
Compiling SPA styles...
(node:11044) Warning: a promise was created in a handler at fs.js:149:15 but was not returned from it, see http://goo.gl/rRqMUw
    at Object.ret [as readFileAsync] (eval at makeNodePromisifiedEval (D:\wwwroot\WebView\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:8:21)
Compiling SPA scripts...
Writing SPA main file...
Parsing 0 Markdown file(s)...
Processing 0 HTML file(s)...
Compiling Docma (Web) Core...
Compiling SPA partials...
Writing docma-web.js ...

Documentation is built successfully...

Configured SPA Routes:

type  name   path   contentPath
----  -----  -----  -----------
api   _def_  /?api  null
```

The template is as follows (all the js files are at ./scripts/*.js and the webpage is at webview.html

```
{
    "name": "WebView Documentation",
    "author": "Draper Laboratory",
    "version": "1.7.0",
    "license": "Private",
    "main": "webview.html",
    "options": {
        "title": "WebView Documetation",
        "sidebar": true,
        "collapsed": false,
        "outline": "tree", 
        "badges": true,
        "symbolMeta": false,
        "search": true,
        "navbar": true,
        "navItems": []
    },
    "compile": {

    },
    "ignore": [
        "libs/**",
        "node_modules/**",
        "*.md",
        "LICENSE"
    ]
}
```

**Comment by onury** [comment]
You are incorrectly using the template configuration file. That's for template developers.

You should instead create a docma.config.json for your build configuration. See [Docma's own config file](https://github.com/onury/docma/blob/master/docma.config.json) for an example... And pls read the [docs](https://onury.io/docma/?api=docma#Docma~BuildConfiguration).
