### ISSUE TITLE
CLI broken for node 8.0.0

### ISSUE THREAD

**Issue by aaronmallen** [onury/docma#61]
All CLI commands fail for node v8.0.0

```bash
$ node -v
v8.0.0

$ npm -v
6.4.1

$ node_modules/.bin/docma -v
$HOME/$MY_PROJECT/node_modules/got/source/create.js:61
	got.stream = (url, options) => got(url, {...options, stream: true});
	                                         ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> ($HOME/$MY_PROJECT/node_modules/got/source/index.js:3:16)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
```

```json
// npm-shrinwrap.json
  "docma": {
      "version": "3.0.0",
      "resolved": "https://registry.npmjs.org/docma/-/docma-3.0.0.tgz",
      "integrity": "sha512-9EnAOkLIIk1D0xFAJd2mKyNX38pRixTBX2+qnlrQfpi0r83jo17r34r7KKq8y5ICOzouRkTVwzteqQEV4w5ulw==",
      "dev": true,
      "requires": {
        "bluebird": "^3.5.3",
        "chalk": "^2.4.1",
        "docma-template-zebra": "^2.2.0",
        "dustjs-linkedin": "^2.7.5",
        "easy-table": "^1.1.1",
        "express": "^4.16.4",
        "fs-extra": "^7.0.1",
        "glob": "^7.1.3",
        "gzip-size": "^5.0.0",
        "inquirer": "^6.2.0",
        "jsdoc-x": "^4.0.0",
        "jsdom": "^13.0.0",
        "less": "^3.8.1",
        "less-plugin-clean-css": "^1.5.1",
        "lodash": "^4.17.11",
        "marked": "^0.5.1",
        "npm-name": "^5.0.1",
        "semver": "^5.6.0",
        "serve-static": "^1.13.2",
        "strip-json-comments": "^2.0.1",
        "uglify-js": "^3.4.9",
        "yargs": "^12.0.4"
      }
    }
```

**Comment by onury** [comment]
There is nothing related to docma in your stack trace.
